# Generated by Django 5.1.1 on 2024-09-23 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_email_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='content',
            field=models.TextField(default='축하합니다 ! 쿠폰이 발급되었습니다, '),
        ),
    ]
