# Generated by Django 5.1.1 on 2024-09-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_coupon_is_downloaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='description',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
