# Generated by Django 5.1.1 on 2024-09-23 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_coupon_description_coupon_discount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='code',
        ),
        migrations.AddField(
            model_name='coupon',
            name='email',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.email', unique=True),
        ),
    ]
